### ISSUE TITLE
Fixed ATD Street Segments Look Up Web Map/App

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-geospatial#179]
Christina Tremel
SMB

Said that the geocoder was not longer working properly

**Comment by dianamartin** [comment]
I opened the web map to see if there was an issue, there was a basemap issue. I went into AGO Assistant to change the service URL to the latest state plane grey scale basemap. 

Opened the web application and updated the search widget. The geo code locator URL was not longer usable. I found the latest service URL and fixed it. Had user test and confirm searching was fixed.

**Comment by jaime-mckeown** [comment]
The basemap for the Traffic Counts Web Map needed to be fixed. Thank you @dianamartin for the new map URL.
