### ISSUE TITLE
GIS Install and Account form for David Bracken

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-geospatial#21]
Steven Romero called me to say that David Bracken needed GIS on his computer.

**Comment by dianamartin** [comment]
Emailed David, Steven and Jaime. Giving instructions to return form to Jaime.

**Comment by dianamartin** [comment]
I accidentally closed this..

**Comment by jaime-mckeown** [comment]
In David's request he stated he needs ArcGIS for viewing GIS data. I asked Diana about this, and she said we are trying to move GIS viewers to AGOL. I then emailed David suggesting that he try AGOL first since he doesn't need to edit data. I shared a link for logging in to AGOL.

**Comment by jaime-mckeown** [comment]
Eric Bollich replied that he wants all his users to have ArcGIS. I submitted a CTM request for an ArcGIS and GISDM database account creation for David.
