### ISSUE TITLE
Parking Inventory Data Migration

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#23]
- About: Create editing application of parking inventory
- Stakeholders: Parking Enforcement Management
- Resources:
Data Dictionary: g:\ATD\ATD_GIS\01_ADMIN\DATA_MANAGEMENT\Data_Migration_parking\parking_inventory\data_dictionary
Testing: Mxd g:\ATD\ATD_GIS\Parking_Enf_Mgmt\working
Requested by: Tracy Linder

**Comment by jaime-mckeown** [comment]
4/10/2019
- Diana shared the background of this project with Matt and I. She went over the relationships between the parking restrictions table, meters, parking spaces, parking zones, and block segments.
- I've been looking at the Feature Layers in the Parking Inventory Web Map and the feature classes on GISMAINTdev
- Comparing the Spreadsheets that she already created referencing the data, creating one for myself to help myself to follow what I'm looking at.
- Got a screen shot of the fields required in AMANDA. Using this to determine what layers have needed fields, etc.

**Comment by jaime-mckeown** [comment]
4/11/2019
- Finished field comparisons between AMANDA requirements table, AGOL and MAINTdev table/feature classes to determine what fields were duplicated where and find the fields that can be moved to the parking_restrictions table to minimize duplication across the feature classes.
- Created myself a Spreadsheet to see what's where and what's going to be moved to the table.
- Discussed my ideas with Diana, clarifying some things I had questions about. I will start creating a new table and feature classes tomorrow, then move a copy of the AGOL data into each of the layers.

**Comment by jaime-mckeown** [comment]
4/12/2019
- Started working on the restricted table, exported data from AGOL to begin figuring out data structure.
- Talked to John about project, we will be meeting Monday to discuss the direction, he asked me to look more at Attribute Assistant, spend some time reading up online.
- Had a discussion with Bryan Thompson about Attribute Assistant, how they use it, and why they are moving away from using the tool.

**Comment by jaime-mckeown** [comment]
4/15/2019
- Discussion with John on fields that are in the restricted table and ease of editing relationship classes.
- Did more research on editing relationship classes, looks really basic by using the attribute window to see the related data, did not find anything about setting up spatial views.
- Started comparing the MAINTdev data to what I exported from AGOL. Need to come up with a plan of attack for migrating data.

**Comment by jaime-mckeown** [comment]
4/17/2019
- Created new feature classes and table on MAINTdev with slightly new formats.
- Created a comparison Spreadsheet to show differences between old and new. Need to verify formats before moving on to create new relationship classes, etc.

**Comment by jaime-mckeown** [comment]
4/18/2019
- Setup domains on Parking Inventory Data, made notes of new domains to possibly add for cleaner editing.
- Discussed Parking Inventory Management Project with Joseph. He helped me to better understand his requirements of the data and processes. I will be sending him an updated schema for the data to get his input for moving forward.

**Comment by jaime-mckeown** [comment]
4/19/2019
- Created a clean Spreadsheet to show the data schema changes from GISMAINTdev from last year to what's current. Will be sending to Joseph to get feedback from him to make sure this will work best for their needs.
- Compare the Spreadsheet and Shapefile he sent me to find the best solution regarding the problems joining SEGMENT_IDs to PARKING_PAY_IDs.

**Comment by jaime-mckeown** [comment]
4/22/2019
- Emailed Joseph Spreadsheet for schema changes, haven't heard back.
- Starting looking into data he's having issues with joining between the table and layer.

**Comment by jaime-mckeown** [comment]
4/23/2109
- Figured out what Joseph needed to do to get the data to properly join. Emailed him a zipped FGDB with the data for example.

**Comment by jaime-mckeown** [comment]
4/25/2019
- Received feedback from Joseph on data schema. We discussed his changes, and came to an agreement for all the layers / table schema. I made the changes to the fields, then ran into a road block with the old data on GISMAINTdev as it was locked by AGOL. Need to get in touch with Sam Adams at CTM to remove the locks, he's been unavailable all afternoon.

**Comment by jaime-mckeown** [comment]
4/29/2019
- Started looking through GIS data and directories for data resembling the parking districts that Joseph mentioned for using to house the pay information instead of in the table. Found a shapefile and old PDF map, sent to Joseph for feedback.

**Comment by jaime-mckeown** [comment]
4/30/2019
- Talked to Joseph about the PDF I sent him, found what he was talking about. Will use that layer to see if I can make a usable layer for housing the pay information.

**Comment by jaime-mckeown** [comment]
5/1/2019
- Worked on creating a polygon layer based on the ROW layer, breaking it up by street segments for each side of the street, further breaking it up for segments that have multiple pay types (i.e. 3 hour and 5 hour parking). I should have enough of an area to change the schema for the other data to test out this idea.

**Comment by jaime-mckeown** [comment]
5/3/2019
- I finally had a mental breakthrough today, went through a few iterations before I finally figured it out. Since there can be many zones to one pay station and many single spaced meters to one zone, I spent some time trying to figure out how best to deal with this. Thought about making them 2 separate layers which eventually sent me down the path towards one layer with a many-many relationship. It took a few tries to get it right, but I think I finally got a many-to-many relationship to work between parking_zones and parking_paystation_meters. It is a manual process to make the relationship between the layers, but all of the data needs to be re-entered manually since it is changing drastically.

**Comment by jaime-mckeown** [comment]
- Tracy has not verified AMANDA fields as of yet, need to hear back from her if they are still the same requirements.
- Added more sample data to test theory for parking_paystation_meters with parking_zones with many-to-many relationship.
- Testing Oracle Trigger for unique ID fields with a separate layer. I think this option will work well for Parking Inventory data, will need to work with Mark Hawkins at CTM once we are ready to move forward with conversion.

**Comment by jaime-mckeown** [comment]
@johnclary
- I did some research for how to symbolize a layer based on related tables. The only way to use any fields in the table is that a join must be created, and because many relationships exist the join must be exported in order to see all of the records.
- If we went this route, the only way to symbolize all zone types would be to use cartographic representations since the exported records from the join would be coincident. This will cause a problem with symbology in AGOL as cartographic representations don't really work. I read about a work-around, but it was cumbersome.
- So, I feel like I'm back to square one here. If all the data needs to continue to be symbolized the same way, I can move all the parking_restriction table fields into the parking_zone layer. The overall new schema removes the problem with duplicate fields across multiple layers. We can keep the relationships between parking_zones and parking_spaces / parking_paystation_meters for connectivity and ease of editing.
- Another positive with this approach is that less editing will be required to move the data into the new schema as the parking_zones would stay separate.

**Comment by johnclary** [comment]
thanks @jaime-mckeown. i wonder to what extent joins (or more specifically, spatial views) might suit our symbology needs. the main symbology challenge is displaying the zones with attributes from the parking_restrictions table, right? in which case perhaps we could layer multiple spatial views of the restrictions + zones with different symbologies ( e.g. one view/layer for each restriction type).

what other symbology challenges (besides zones + restrictions) do you see here?

**Comment by jaime-mckeown** [comment]
@johnclary It's more then just a join to symbolize. You have to export the join to the same GDB in order to see all of the data since there is a one-to-many join.  Additionally, we will have multiple zones on top of each other so that's another problem with symbology.

**Comment by johnclary** [comment]
OK. Looking forward to more discussion when we meet on Friday.  In the meantime, take a quick look (if you haven't already) on the spatial views docs, because I'm under the impression that if you do this on SDE you don't need to export.

http://desktop.arcgis.com/en/arcmap/10.3/manage-data/using-sql-with-gdbs/example-creating-a-spatial-view-in-oracle-with-sql.htm

**Comment by jaime-mckeown** [comment]
Spent some time today trying to figure out how to create a spatial view for the parking_restrictions table info related to the parking_zones. Successfully created a spatial view, then moved on to being able to publish the view to a feature service in AGOL to be used in a Web Map. Finally making progress, will be ready to discuss with John on Friday.

**Comment by jaime-mckeown** [comment]
Finally got back to the parking project today and created more sample data. Re-published the 2 spatial views for parking zones to AGOL. Started working on publishing paystations_meters to AGOL, but finding that the symbology won't draw without the related data.

**Comment by jaime-mckeown** [comment]
- Been working on trying to get the parking data into AGOL with the relationship classes.
- Finally spoke with Tracy about the AMANDA requirements for the GIS parking data. It looks like we have all the fields they will need, but that can change as they start working on it. I need to ensure that the data does not have null values and send a copy of the sample data to Sean McClurkan, Ashley Parsons, and Tracy Linder.

**Comment by jaime-mckeown** [comment]
Spoke with Joseph and Diana about some of the fields that are still null to try and get some data coded so I can get the sample data sent over to Sean and Ashley.  Tracy is ok with made-up values as they are more interested in the field types and how the data is setup currently. Got the fields mostly coded, will email the FGDB over today.

**Comment by jaime-mckeown** [comment]
Started working on transitioning data from AGOL to SDE, will work on it as I have time to get it moved over.

**Comment by jaime-mckeown** [comment]
Continue with transition, started with block_segments.

**Comment by jaime-mckeown** [comment]
Phone conversation with Sean from CTM about parking data:

> - Sean spoke about the block_segments layer for a bit. He wanted to know why we were duplicating data that was already available in the street segment layer instead of just relating to it and using it directly. He does not need the Block Name from this layer for AMANDA as he can get it directly from the street segment layer. I told him that I won’t be changing the layer just because he deemed it unnecessary and that I would talk to you about it.
> 
> - In regards to meters and pay-stations, he is asking that they be separated into 2 layers so we can keep only one-to-many relationships between data and not have many-to-many relationships due to needing the intersection table with those. As separate layers, the meters would have a many-to-one relationship to parking zones and pay-stations would have a one-to-many relationship to parking zones. 
> 
> - In regards to parking spaces, he is asking for the parking spaces to be related to the meters/pay-stations instead of to the parking zones. He sees the data as hierarchical where parking spaces relate to meters/pay-stations and meters/pay-stations relate to parking zones. With this idea, parking spaces would then have to be separated into 2 layers as well since there are parking spaces that are not associated with meters/pay-stations, only parking zones, so they would have a different relationship. 
> 
> - He also stated that he can get all the data into the new schema with minimal work which of course I questioned since it doesn’t make sense how he can do that. He asked me to send him a new export of the parking data from AGOL. I will send him a FGDB of the data for him to work with.
>

**Comment by jaime-mckeown** [comment]
Met with Joseph yesterday. I showed him the new schema and talked about the need for parking spaces to relate directly to meters/pay stations. We determined that they need to be related, therefore changing the schema for the relationship classes. We are meeting with Jeremy on Tuesday since he forgot to attend yesterdays meeting.

**Comment by jaime-mckeown** [comment]
Met with Joseph and Jeremy last week. The conversation brought new requirements of the data to my attention.
- Jeremy needs to be able to make mass changes to the data.
- Jeremy also needs BLOCK_NAME field available on each of the data layers for reporting purposes
After looking into both of these I decided it was best to meet with John and Diana before spending too much time as editing data with relationship classes isn't as easy as it would seem.

Today I met with John and Diana to discuss the issues
- I am going to install ArcGIS Pro to see if that allows for easier editing with relationship classes for mass editing.
- I need to email Jeremy and Joseph and get their most important requirements for editing this data, reports that they create, etc. so we are not moving forward not knowing all aspects.
- Will continue to meet with John and Diana to ensure the project continues to move forward.

**Comment by jaime-mckeown** [comment]
Create a PowerPoint to present project to DTS at team meeting next Tuesday.

**Comment by johnclary** [comment]
@jaime-mckeown add issues to this epic for each feature class / migration step
