### ISSUE TITLE
GIMOB Meeting - September 2019

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#233]
Attend the month GIMOB Meeting. Will add my notes to OneNote referenced in the Epic.

**Comment by jaime-mckeown** [comment]
Alan attended on my behalf.

**Comment by alan-deanda** [comment]
@jaime-mckeown  I've added my notes from the GIMOB meeting to the OneNote doc from the Epic

**Comment by jaime-mckeown** [comment]
Great, thanks @alan-deanda !

**Comment by jaime-mckeown** [comment]
September GIMOB Meeting notes:

	• Installations going to H-drive instead of C-drive.
		○ Danny Haverlah hasn't seen this happen, and he's on 10.4.1 going to 10.6
 
	• Slow edits on SDE - mentioned to Bruce, super slow for speaker; it wasn't before. Watershed agrees, slow edits. They tie it to DM, it has performance issues that haven't pinned down yet.
		○  Having layers from DM in mxd creates performance issues on desktop. 
		○ Mxd goes slow after adding a feature class from DM. 
		○ Workaround: export layer from DM onto FGDB on H, G, or C drive.
		○ This has apparently not been an issue on ArcPro.
		○  Speaker noted that every open ESRI ticket is looked at in monthly meeting between COA/ESRI.
		○   Interim Solution: keep opening tickets and sending them to ESRI.
		○  Someone (unclear who was speaking) apparently has a patch for this problem.
			▪ Patch may have been for their specific experience with this issue, and perhaps not widely applicable.
		
	•  Discussion of pros and cons of Microsoft Teams vs Bloomfire
		○ Bloomfire will continue to be used until Teams can do everything Bloomfire can.
	
	• Demo, discussion of ARCGIS URBAN
		○ Planning tool
			▪ Draw 3D buildings with attributes (square footage, usage, etc.)
				•  SF CASE STUDY
			▪  Relies on LIDAR Data
		○  Speaker wants to know if COA is interested in purchasing.
