### ISSUE TITLE
Bike Rack data collection meeting with Parking

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-geospatial#286]
### Notes from meeting with Parking Enforcement (PE) to discuss bike rack data collection ### 
* PE is going to purchase tablets for general field work, and to collect the location of existing bike racks not currently mapped. 
* PE employees need to be trained on how to use collector or AGOL web app to collect point data to represent each rack. DTS GIS will develop a simple AGOL collecting training similar to the one that ROW employees receive for SXSW.
    * Documentation wikis will also be provided.
* To evaluate the status of existing bike racks, PE will note the general location of bike racks in the central city, and then do more detailed site inspections.
* Once existing bike racks within the central city have been assessed, PE will begin to maintain and re-install new bike racks
* A knack data tracker system, similar to the one created for Signs and Markings, would be useful in tracking the work being done on each rack.

### Next steps ###
* Once Active Transportation has QA-QC-ed existing bike rack data, DTS GIS will move the data to AGOL for data collection from PE
* Create simple point feature service to record general location of existing bike racks
* Train PE staff on field data collection.
* Scope of data tracker/work order integration TBD

**Comment by alan-deanda** [comment]
@johnclary , here are my notes from my meeting with Parking Enforcement

**Comment by johnclary** [comment]
@alan-deanda do you have a sense of PE's timeline? this is big enough that we should run it through intake w/ @amenity on point for the future project. cc @TracyLinder

**Comment by alan-deanda** [comment]
@johnclary The data capture for all bike racks within the central area might take 6 months. After that they'll continue to collect data outside of the central area. We'll want to train them within a month, as they'll be ordering tablets soon, and while they have an iPad they could use now, I want everyone to have a tablet and at the training. 
Until we have a work order system for them, they're able to keep track of Phase 1 installations and repairs on GIS. Ideally for them, we would have the system in place by the time they have to do follow-up work, to have a history of the work being done per site.
