### ISSUE TITLE
GIS Support AGOL Admin for TDSD - N. Saeedi

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#287]
Nazlie needed some guidance for how to use AGOL. She is looking for help to get TDSD going completely on AGOL.

**Comment by jaime-mckeown** [comment]
- Created new Group in AGOL for TDSD
- Added current members to the group
- Notified Nazlie of users that need to create AGOL accounts
- Submitted CTM HD Ticket for Nazlie's user role to be changed to a COA User

**Comment by jaime-mckeown** [comment]
Nazlie's account was changed. Added her and the other people that needed to create accounts to the TDSD Group in AGOL.

**Comment by jaime-mckeown** [comment]
- Everyone in the group is now in AGOL and has been added to the TDSD group.
- Nazlie sent me the Mxd that the group is currently using in ArcMap, will create a Web Map for them on AGOL in the TDSD Group.

**Comment by jaime-mckeown** [comment]
- Created a TDSD Folder in AGOL
- Started working on the Web Map using the Mxd that Nazlie sent me
- Found many layers in the Mxd that are in GISDM, but are not in AGOL
- Submitted CTM help desk ticket to have them added to AGOL
- Other layers are out of date, i.e. Cap Metro layers

**Comment by johnclary** [comment]
@jaime-mckeown create issue for the webmap and close this please.

**Comment by jaime-mckeown** [comment]
Created new Issue for the Web Map she has requested.
