### ISSUE TITLE
GIS Utility Mapping for ROW

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#295]
**The project Index is[ here](https://github.com/cityofaustin/atd-data-tech/issues/815), in data-tech.** 

ROW is asking for all GIS utility data (public/private) to be collected and maintained for the Austin Utility and Location Coordination Committee (AULCC) for the City of Austin.

See GIS Mapping of Utilities Meeting Notes for comments from the 1st meeting.

**Comment by TracyLinder** [comment]
## Update 10/22/19:
This is a very large project that needs considerable PM resources to perform scoping/discovery. This will go to the backlog until the ROW Project update on 10/28.

**Comment by TracyLinder** [comment]
@johnclary I'm taking the Index label off of this. I thought we had decided that all Index issues should be in data-tech? 
The Index for this is [#815](https://github.com/cityofaustin/atd-data-tech/issues/815)
