### ISSUE TITLE
Weekly Update: AMANDA street closure - FME to Python

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#3]
Change the weekly process for updating the data for the Street_Events_Amanda feature layer to a python script from an FME Workbench.

**Comment by jaime-mckeown** [comment]
Wrote a python script to replace the FME Workbench that had to continually be modified depending on how the AMANDA user entered the name of the Event. Python can strip to extra blanks regardless of how many there are.

**Comment by johnclary** [comment]
@jaime-mckeown add  your code and docs to github and let me know if you need help.

**Comment by jaime-mckeown** [comment]
- Need to update the documentation for running the weekly update.
- Will test this process out again next Monday to see if I need to make any changes.

**Comment by jaime-mckeown** [comment]
- Documentation has been updated.
- Script ran as expected.
