### ISSUE TITLE
Define Maintainer Roles and Responsbilities

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-geospatial#306]

**Comment by alan-deanda** [comment]
### Next steps ###

Add these roles and responsibilities to wiki - create draw.io diagram

**Comment by alan-deanda** [comment]
Need to schedule a meeting with Active Transportation to confirm roles and responsibilities.

**Comment by johnclary** [comment]
@alan-deanda schedule it!

**Comment by johnclary** [comment]
Sophia will create a spec sheet of bike racks and hardware
