### ISSUE TITLE
AGOL Training w/ TDSD

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-geospatial#311]
Nazlie from the TDSD Division has asked me to get her team going using AGOL. They are new users, so having a training session will help them to get more comfortable with the software.

**Comment by jaime-mckeown** [comment]
There is an upcoming Intro to AGOL Workshop coming up in February, emailed Nazlie to let her group know in case they would like to register.

**Comment by johnclary** [comment]
Waiting for confirmation from Nazlie if the Esri training is sufficient.
