### ISSUE TITLE
Research for PHB Ranking Criteria after 1st Meeting

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#332]
From 1st meeting:
- Contact Social Services Austin or Travis County to see if they have a list of support service locations
- Look into creating population density based on landuse within each Census Tract

**Comment by jaime-mckeown** [comment]
- Austin and Travis County both had locations listed our their websites. The Central Texas Food Bank has a comprehensive list on it's website. Created an Excel Spreadsheet broken down by location and what services are offered.
- Spent some time on the Census Bureaus website trying to figure out how to get data as they have changed it again since the last time I used it. Finally figured out how to get total population by census tract within specific counties.
- Started working with the data in ArcMap along with Landuse data for coming up with population density to present to Renee and Andres at meeting tomorrow.

**Comment by johnclary** [comment]
@jaime-mckeown add your notes here and close. thx

**Comment by jaime-mckeown** [comment]
Opened new Issue for next steps after 2nd meeting.
