### ISSUE TITLE
Get ArcGIS Pro Training

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-geospatial#391]
@jaime-mckeown would you find your materials and give them to @alan-deanda? Alan, optionally enroll in a training class.

**Comment by jaime-mckeown** [comment]
@alan-deanda I saved my Esri course materials to the G drive, it includes the student workbook and data for 5 classes.  G:\ATD\ATD_GIS\03_RESOURCES\Esri_Class_Materials

**Comment by jaime-mckeown** [comment]
Alan requested to take the Migrating to Pro class through the city. Sent the request to CTM for his enrollment.
