### ISSUE TITLE
Import new bike facilities into OSM

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-geospatial#399]

**Comment by alan-deanda** [comment]
Imports are pending approval by OSM community members. I might manually draw and tag new facilities.

**Comment by johnclary** [comment]
Drawing by hand. In progress

**Comment by johnclary** [comment]
@alan-deanda confirm if importing will be necessary

**Comment by alan-deanda** [comment]
Participants in the map-a-thon have continued to meet and make updates to the OSM bike data. They're working off an updated version of the wiki created for the map-a-thon. No importing is necessary.
