### ISSUE TITLE
2019 Trail of Lights Story Map

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#413]
PARD created a map series using Google for this years Trail of Lights. Frances emailed me about doing something easier to use and more visually appealing. Below is the PARD Google map for reference.

https://www.google.com/maps/d/u/1/viewer?hl=en&mid=1o5RyCCDsvq_MASQue4A9YYo17eOQdUTT&ll=30.265837014729456%2C-97.7708343633359&z=16

**Comment by jaime-mckeown** [comment]
- I never received any information from PARD for the road closures, parking, access, etc. Frances told me what was on the Google map was accurate, so I created a point, line, and polygon layers and created data based on the data that was in the map.
- Created multiple Web Maps to use in a Story Map.
- Created a Story Map, configured it, and sent what I had to Frances to see what they think of it.

**Comment by jaime-mckeown** [comment]
- Tested with my phone and tablet last night, needed some re-configuring.
- Re-configured pop-ups to show only needed information.

**Comment by jaime-mckeown** [comment]
Sent to Frances yesterday for feedback.

**Comment by jaime-mckeown** [comment]
Haven't heard back from Frances regarding Story Map. Will close issue and open a new one if she requests changes to the application.

**Comment by johnclary** [comment]
@jaime-mckeown will you put a link to the map in here?

**Comment by johnclary** [comment]
https://austin.maps.arcgis.com/apps/MapSeries/index.html?appid=272a17969d494a908be4200518266d8b

@jaime-mckeown plz fix :)

**Comment by jaime-mckeown** [comment]
@johnclary What did you mean by re-rest the Web App? All the items are shared to the public so there shouldn't be any issues viewing the map...

**Comment by johnclary** [comment]
The maps still do not load for me unless i open a up a private window. Would you ask some of your colleagues to test and confirm that it's just me?

**Comment by jaime-mckeown** [comment]
Asked DTS to verify that the maps are accessible, confirmed. John must have security settings on his laptop preventing him from viewing unless he's in a private page.
