### ISSUE TITLE
Capital Needs Discovery Mapping

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-geospatial#418]
A unified map of about eighty capital projects for the executive team. 

Sharepoint folder with brief, list of projects, etc. 

Requested by Chris M.

**Comment by johnclary** [comment]
@alan-deanda plz create smaller issues as needed

**Comment by johnclary** [comment]
Chris is wrangling project data; Alan is creating features and will create a template/bookmarks for the district maps. Chris is going to finalize maps.

**Comment by alan-deanda** [comment]
I've submitted a draft AGOL map, and I await feedback.

**Comment by johnclary** [comment]
@alan-deanda closing this. please open new issues if needed.
