### ISSUE TITLE
GIS Service Request: CapMetro Routes - Service Changes from August 2019 - ArcGIS Online Layer Updates

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-geospatial#420]
## GIS Service Request ##

**Requester:**
D. Johnstone
**Issue Description:**
Alan,

Is it possible to get the updated GIS layer that reflects the August 2019 service changes for CapMetro onto ArcGIS Online? The only layer I’m seeing in ArcGIS online is one that was updated in March 2019 and maintained by CTM.Publisher. I’m looking for the data to draft a map for the upcoming Cameron/Dessau Roads listening session that would show the transit routes nearby. I was unable to find CMTA routes in the DataMart layers. This seems like a resource that could be used by many ATD divisions. 

Caitlin D’Alton pointed me to the CapMetro’s open data portal: 
https://data.texas.gov/Transportation/CapMetro-Shapefiles-AUGUST-2019/cc78-vvdy 

**Resolution / Service Provided:**

**Comment by jaime-mckeown** [comment]
here's the Issue relating to the request I just submitted to CTM:
https://github.com/cityofaustin/atd-geospatial/issues/426

**Comment by alan-deanda** [comment]
I've notified D. Johnstone the data has been updated.
