### ISSUE TITLE
TDSD Web App Part 2 - N. Saeedi

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#423]
Continue working on Web App, AGOL Group, Admin...

**Comment by johnclary** [comment]
@jaime-mckeown reminder to add this to the data inventory

**Comment by jaime-mckeown** [comment]
Finished modifying the data in the Web Map, sent email to Nazlie to check out the Web App for feedback.

**Comment by jaime-mckeown** [comment]
Still no feedback from Nazlie, will close Issue and create a new one if they request any changes to the Map or App.
