### ISSUE TITLE
CapMetro GIS Data - GISDM_External & AGOL

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#426]
The CapMetro data for Routes, Service Area, and Stops is not staying current on GISDM_External and AGOL. I called Dwayne to find out the best approach for working with CTM on getting this issue resolved. The first step is to submit a help desk ticket to get the question going to CTM.

**Comment by jaime-mckeown** [comment]
Submitted help desk ticket after talking to Dwayne.

**Comment by jaime-mckeown** [comment]
https://github.com/cityofaustin/atd-geospatial/issues/420 request to Alan from a user about CapMetro Data.

**Comment by jaime-mckeown** [comment]
Dwayne is working on this request. Since Cap Metro changes the name of the data each time, they may have an issue automating the process. He will let me know what he finds out.

**Comment by jaime-mckeown** [comment]
- CTM will be updating the schema on the following layers in GISDM_External on 12/5/19:
EXTERNAL.cmta_routes
EXTERNAL.cmta_service_area
EXTERNAL.cmta_stops
- With the new schema provided by CapMetro in GISDM, we can continue to keep it updated using Geodatapusher as new data is released. CTM will not be able to automate the update process as the naming convention changes with every update.
- The layers located in AGOL will also be updated with the new schema after 12/5 so they can be automatically updated by the data living in GISDM_External.

**Comment by johnclary** [comment]
@alan-deanda will close the loop with Dylan once this is done. @jaime-mckeown follow-up w/ capmetro about receiving email notifications when data is updated.

**Comment by jaime-mckeown** [comment]
Emailed Mike Long at Cap Metro to see if he has a distribution list or set update schedule.

**Comment by jaime-mckeown** [comment]
CapMetro data has finally been updated on GISDM_External and AGOL. FYI @alan-deanda for your issue.

**Comment by alan-deanda** [comment]
thanks @jaime-mckeown !
