### ISSUE TITLE
Map of UT-owned Properties

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-geospatial#436]
Rob has requested a map of UT-owned properties in Austin. This should be possible through the TCAD property data. Cole is the point-of-contact to get clarification on map deliverables.

**Comment by johnclary** [comment]
@jaime-mckeown @alan-deanda let's discuss today.

**Comment by jaime-mckeown** [comment]
Selected out all University of Texas owned parcels from TCAD Parcels and created a small map to send to Cole to get feedback on what all Rob would like to see on the map.

**Comment by jaime-mckeown** [comment]
- Cole responded that the small map I created would be fine, also requested a table with properties by address with acreage and $ value.
- Sent Spreadsheet with requested information.

**Comment by jaime-mckeown** [comment]
Cole responded, he will be sending the map and spreadsheet to Rob and will cc John in case Rob has any feedback.

**Comment by jaime-mckeown** [comment]
No feedback received, closing issue.
