### ISSUE TITLE
Smart Trips Story Map - A. Greenstein

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#450]
- Re-create a Story Map that contractors created for Ashley in SDD. She was unaware that content could not be transferred between personal Esri accounts or Organizational accounts.
- It will be much easier to create it for her, then have her do the updates.
- I will need to see about signing her up for an AGOL / Story Map Class so she is more confident in keeping the App updated once it's created.

**Comment by johnclary** [comment]
@jaime-mckeown talk to Sam or Mat Peck about getting a **temporary** headless account for the contractors.

**Comment by jaime-mckeown** [comment]
Emailed Sam about getting a headless account for Smart Trips on AGOL. Sam said I could do that, submitted a CTM request for a new account.

**Comment by jaime-mckeown** [comment]
- Submitted CTM request for headless AGOL account on 12/18, have not heard anything since.
- I also emailed Ashley on 12/18, no response.

> So you had ambassadors create the Story Map and now have consultants you want to maintain it?
> 
> Regarding your question about transferring the Story Map into a headless account, it can’t be transferred, it will have to be re-created in the Austin Texas ArcGIS Organization. If you still have consultants that are available to work on the Story Map, I can submit the request to CTM to get the headless account created. If we do that, can they work on migrating the Story Map into the Austin Texas ArcGIS Online Organization?
> 
> You can continue to use the Story Map as is in its current state, but we can’t edit is as it’s not in our organization.

- Moving Issue to the Backlog since this doesn't seem to be a priority for her.

**Comment by jaime-mckeown** [comment]
CTM created an AGOL account for new headless account, forwarded on to Ashley so she can complete to login process.

**Comment by jaime-mckeown** [comment]
After emailing Ben to see if he could re-send the initial email, Ashley emailed again asking what the status was which means Ben did not resend the initial email. I will reach out to Sam to see if he can help.

**Comment by jaime-mckeown** [comment]
Talked to Sam:
- he emailed info@smarttripsaustin.org a password reset, I am waiting to hear from Ashley if she received it.
- If not, then I will submit a service request to have the email attached to username SmartTrip_austin changed to smarttripsatx@gmail.com and reset the password.

**Comment by jaime-mckeown** [comment]
She still didn't receive an email, had to submit a new request to change email to smarttripsatx@gmail.com. Still waiting to see if she received the email.

**Comment by jaime-mckeown** [comment]
Ashley finally got the login email at the email above. She should be set to have her contractors create the Story Map internally. Closing Issue.
