### ISSUE TITLE
GIMOB Meeting - January 2020

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#455]
Attend the month GIMOB Meeting. Will add my notes to a comment below.

**Comment by johnclary** [comment]
Moving from "new" to "backlog".

**Comment by jaime-mckeown** [comment]
- PAZ Imagine Austin Scope - requesting to have Esri put together a python script to determine whether or not a site is in compliance with Imagine Austin Scope. Passed to get 20 credits to have Esri produce script..
- City-wide AGOL Meeting - Department Admin or Publishers are asked to attend and power users. AGOL Guidance Document will be covered in the meeting and best practices. Mat has an AGOL Teams Page to see more information about AGOL Subcommittee, etc. Next AGOL Subcommittee is 2/19/20
- New GIMOB Chair - vote for new chair of GIMOB, Roxanne Parker was voted in.
- PARD Application - Allison is getting PARD app back from Esri today, she will let everyone know when it's available for download.
- Impervious Cover - Fugro is the new vendor, finances still going through process
- Geoanalytics - CTM is going through a transition. Looking to build easement layer using a contractor plus AW is also editing easements.
   - Streets data is where she is thinking we should get started with to improve the data
   - A couple people brought up that easements are a higher priority then streets data.
   - Jacquie is going to ask all departments to vote on order of importance for the datasets in questions for updating. Create user stories as to why each dataset is important to our department. (Top 3 datasets)
- Started a working group for Homelessness on Teams. Email Mat if you would like to be included in workgroup.
- CTM is hiring a contractor for migration to ArcGIS Pro who will be with CTM for hopefully a couple years.
- Knowledge Base had a training session that went well. They would like to re-vamp Bloomfire.
- CTM is encouraging users to start moving to Teams as Skype is going away in 2021.
- Basemap and Geocoding Server update on 1/4/20.
- 10.8.0 will be coming out soon, but don't upgrade until the license manager is upgraded.
- All GeoCortex Applications will be converted over to the new Servers via CTM.
- Don't upgrade to ArcGIS Pro to 2.5 until CTM lets us know it's ok to upgrade.
- CTECC, streets being worked on by GeoComm, should be done by end of January.
- E911 is going to NextGen 911, working on getting the new schema to move forward.
- PW would like to add CAD data to ATDs Markings data. Bryan T. will get in touch with me about this request. They would like to create a subcommittee for CAD Drawings for buildings.
