### ISSUE TITLE
Meeting Notes: AECOM Traffic Registry Update 12/11/2019

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-geospatial#464]
### Objective 
Receive update from AECOM on Traffic Registry work
### Participants
C. Musgrove, K. Williams, A. De Anda
### Agenda
Create agenda from [this template](https://docs.google.com/document/d/1d_49KW5C_vSz8Bs50v-cxyIJuTNJMwMrh7ypcxRHgZI/edit#) and save as a publicly-visible file in Google Drive.

------
- [x] Schedule meeting
- [x] Meet and take notes in agenda doc
- [ ] Create resulting issues

-----
Notes:

Update from Chase:
% of verified active regulations: 38%

Over 41% of active regulations in the correct location reviewed by AECOM

Regulations in need of atd review = 35.29%

Priority 1 review data: close to 90%

Stop sign regulations: stop signs are points which required new automation, since the other regulations are regularly lines. This has been improved upon, and stop signs are now moved to their appropriate locations. (Chase demoed his automation, it works great.)

Chase will send data to Alan & Diana over weTransfer that includes the over 41% in the correct location reviewed by AECOM.

AECOM is curious if there is any feedback on data sent previously. If there isn't, then they'll keep going as they have been so far.

**Comment by alan-deanda** [comment]
@johnclary  @dianamartin  here are my notes from the meeting with AECOM.

**Comment by johnclary** [comment]
@alan-deanda can you clarify, when did AECOMM previously send data? did you review it? thanks.
