### ISSUE TITLE
ADA Web Map / App

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#469]
From David:

> We have a new ADA volunteer coordinator with Parking Enterprise and he was wondering who administrates the following map.
> https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=6336047abc774c3fad4cf5aed48054e6
> Ideally he would like to build it out for programs that he is working on but I have been having trouble tracking down who is currently administrating it.  Would you be able to point me in the right direction? 
>

**Comment by jaime-mckeown** [comment]
Responded to David:
- Let him know the standard for Maps/Apps shared to the public that the ATD Publisher account would be the owner and that we can change the ownership over so the ADA volunteer coordinator can modify them.
- Asked if he has an internal email account as it's needed to login to AGOL.

**Comment by jaime-mckeown** [comment]
- Emailed David and Elayna since they do not have AGOL accounts. Sent instructions for logging in for the first time.
- Also sent information for the AGOL Workshop in case they are not already familiar with AGOL.
- Changed to Sprint 14.

**Comment by johnclary** [comment]
@jaime-mckeown would you add this to the data inventory? if it's not already there?

**Comment by jaime-mckeown** [comment]
Added to the data inventory.

**Comment by jaime-mckeown** [comment]
I haven't heard back from Allen about working with the Web Map / App. I will open a new Issue when he is ready for my help.
