### ISSUE TITLE
CIP Feature Class Updates

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-geospatial#47]
This will be a new recurring task that requires the GIS team to map capital improvement projects (CIP) in the shared "CIP Feature Class" layer.

[This report](https://gcc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmstr.austintexas.gov%2FMicroStrategy%2Fasp%2FMain.aspx%3Fevt%3D4001%26src%3DMain.aspx.4001%26visMode%3D0%26reportViewMode%3D1%26reportID%3D8B573A5F400F68C26D4B1398A87ABACC%26Server%3DCOAMSTRP01%26Project%3DFinancial%2520Services%2520Analytics%26Port%3D0%26share%3D1&data=02%7C01%7CJohn.Clary%40austintexas.gov%7C81afc620f7fc41edaac208d6d36350e7%7C5c5e19f6a6ab4b45b1d0be4608a9a67f%7C0%7C0%7C636928820855704736&sdata=6zAjbuY3OSYNNuNb%2B5xDe1yBMXCGZgxCsgOt7qcRGhY%3D&reserved=0) lists which projects need to be mapped.

Current task is to get access to eCapris, which is where all project data is stored.

**Comment by johnclary** [comment]
Requested eCapris access for team today. Waiting to hear from CTM.

**Comment by alan-deanda** [comment]
- [x] Added all CIPs to Feature Classes from spreadsheet.
- [ ] Active Transportation Barrier Removal CIPs

**Comment by alan-deanda** [comment]
@johnclary I haven't received word from Cole Kitten on when the Active Transportation Barrier Removal CIPs might be ready for me to include into the CIP FC. Should I move this issue to icebox or backlog?

**Comment by johnclary** [comment]
Would you follow up with Cole again? Then you can close this and reopen if/when he responds. Thanks.

________________________________

**Comment by alan-deanda** [comment]
Cole has not indicated whether more projects need to be added at the moment. I will close this issue and create a new one if we ever add the barrier removal projects to the CIP FC.
