### ISSUE TITLE
Austin Opportunity Zones Map - K. Taylor

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#478]
- Karla is requesting a large printed map like the one she saw in this article in the Austin Monitor.
https://www.austinmonitor.com/stories/2019/12/austins-opportunity-zones-expected-to-see-increased-investment-development-in-2020/
- Contact Economic Development for more details on the map.

**Comment by jaime-mckeown** [comment]
Emailed Donald Jackson about the map that was used in the article.

**Comment by jaime-mckeown** [comment]
No response from Donald.

**Comment by jaime-mckeown** [comment]
- Found the Opportunity Zones data in AGOL, created a new map similar to the one Karla saw in the article. Will send Karla a PDF first before printing.
- Will also send her a link to this Web App created by Neighborhood Housing and Community Development. http://austin.maps.arcgis.com/apps/webappviewer/index.html?id=e49000a25cf749b88c4be0c6730fe621

**Comment by jaime-mckeown** [comment]
Emailed Karla again to see what map she would like printed after not hearing back.

**Comment by johnclary** [comment]
No response. Closing now until we hear back.
