### ISSUE TITLE
Meeting with Sophia about all things bike racks

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-geospatial#509]
### Objective 
- [ ] Standardize bike rack specs with Sophia
- [ ] How should citizens submit requests? 311?
- [ ] Draft spec document 

### Participants
Alan, Sophia

### Agenda

------
- [x] Schedule meeting
- [x] Meet and take notes in agenda doc
- [ ] Create resulting issues

**Comment by alan-deanda** [comment]
Sophia was out sick on the day of our meeting, will need to reschedule.

**Comment by johnclary** [comment]
Scheduled for 2/20

**Comment by alan-deanda** [comment]
Met with Sophia yesterday.
We'll go back to dealing with final specs and 311 data in the future, as temporary bike racks for SXSW are a higher priority at the moment. I'll create separate issues for final specs and 311 data. Changing estimate to 1 and closing this issue.
