### ISSUE TITLE
Create Vector Tile Layer of Strava Heatmap data

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-geospatial#515]

**Comment by johnclary** [comment]
@alan-deanda would note summarizing your work here?

**Comment by alan-deanda** [comment]
Strava included TIF heatmaps of pedestrian and bike activity with their 2019 Q2 data. The heatmap covers a wide section of Central Texas that includes Austin but reaches far beyond it.
The TIF contained 4 bands. Displaying it with 3 bands (red = 1, green = 2, blue = 3) resulted in a lot of noise data, and the data is best displayed by stretching band 2 with a percent clip (default settings), but displaying the background color (0) with no color.
The color scheme was requested to go from Blue to Red with as few colors as possible in between. In ArcPro one chooses the linear algorithm, and in ArcMap one chooses Lab LCh.

To share the heatmap through AGOL it is necessary to convert the raster to polygon, filtering out the noise through a definition query in the range of `gridcode >51` to `gridcode > 151' as preferred. The polygon then needs to be converted to a vector tile package in ArcPro, published and shared. It is possible to simply publish a feature service of the polygon without converting it to a vector tile, but the drawing performance is much slower.
