### ISSUE TITLE
GIS Support - D. Borkar-Desai

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-geospatial#53]
Dipti called me and left a voicemail and said she needed some GIS Support

**Comment by dianamartin** [comment]
Emailed Dipti to follow-up and cc'd Jaime so that she'd know who the new ATD GIS SPOC is.

**Comment by jaime-mckeown** [comment]
- Dipti just called. Her computer was re-imaged so she lost her connection to GISDM. I helped her create a connection to GISDM, she was able to connect the the layers.
- I asked her if she's ever used ArcGIS Online, which she had not. I told her we had a comprehensive Web Application that probably had all the layers she needed and didn't require using ArcGIS Desktop. Will send her a link to the Web App so she can give it a try.
- Closing Issue.
