### ISSUE TITLE
Signalized Intersection Aerial PDFs

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#532]
- Brian is looking for PDFs of all the signalized intersections in COA at at 200' - 300' radius with an aerial view.
- He is hoping to get this in the next month.
- He would like me to show him a couple extent examples before creating them all so he can decide what extent will work best.

- Signalized intersections layer, buffer for each signal at desired extent, create Data Driven Pages, export PDFs for all pages.

**Comment by jaime-mckeown** [comment]
- Started working on this request yesterday. There are 1148 signals in the traffic signal and pedestrian signal layer, which means a large amount of PDFs to create that will take up a lot of space.
- Brian changes his request to see 100' and 150' buffers, sent him an example of both to compare.

**Comment by johnclary** [comment]
```python
import requests # install this library

response = requests.get("https://data.austintexas.gov/resource/p53x-x73x.json?$limit=10000")

data = respose.json() # list dictionaries where each dict is a signal with a "latitude" and "longitude" field

for signal in data:
    latitude = signal["location_latitude"]
    longitude = signal["location_longitude"]
```
