### ISSUE TITLE
GIS Service Request: Publish AGOL School Zones Map

### ISSUE THREAD

**Issue by alan-deanda** [cityofaustin/atd-geospatial#553]
## GIS Service Request ##

**Requester:**
A. Applewhite
**Issue Description:**
Create and publish a web map that displays the school zones layer from MAINT.
**Resolution / Service Provided:**
Map created.

**Comment by alan-deanda** [comment]
@amenity  the map can be found [here](https://austin.maps.arcgis.com/home/webmap/viewer.html?webmap=f985a3044e254b5bb67425747d4bbc72) using COACD logins.

**Comment by amenity** [comment]
This is perfect, gracias! :sparkles: :world_map: :school:
