### ISSUE TITLE
GIMOB Meeting - February 2020

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#574]
Attend the month GIMOB Meeting. Will add my notes to a comment below.

**Comment by dianamartin** [comment]
## Diana's Meeting Notes
### APD is asking for an ESRI Health Check, they want to pin point performance issues 
To review and optimize Public Safety architecture 
28 hrs of consulting services 
77 credits 

328 credits 
Allison  - motions, Bryan - seconds 
Motion passes - Approved! 

### Map Products Guideline Document - Mat Peck 
Disclaimer on a map 
Didn't have a response 

Do's and Don'ts for physical map products 

User's question was: 1 document/several maps. Does the disclaimer have to be on every inset map or in the background somewhere.  

What to show static map documents and web map documents.  
Mat would like to lead the project.  

 ### Technical News - Migration: moving our data center Sun, Feb 23rd 
All the databases for AMANDA, MAXIMO, GIS databases  4 am - 10 am.  
All GeoCortex apps: Jurisdictions, ROWPACT, etc… 
Will shut down FME servers workbenches, everything 
Will be down, all services, locators, all web maps/apps.  
Shutting down DEV servers on Friday. Things will come back on Sunday.  

_Reboot computer that weekend. 
Get What's Happening, forward email to department users. We recommend all GIS users to reboot that weekend._

### Data Purchases: Planet Imagery - FY 2021 
Buying new ortho-imagery 
Won't have funding until Oct 2020 

![image](https://user-images.githubusercontent.com/21112975/74265800-c7f34300-4cc8-11ea-97b2-55a829956fe5.png)

**LiDAR 2021 AOI Map**
Flying Jan 2021 
4 m  
Higher accuracy data 

 ### New Pro Migration Project Manager Introduction - Lady..(Don't have her name) 
By next operating board meeting will have draft charter 
Where they're going with the project 

### Enterprise Data Projects - Jacquie 
Measuring the needs of the data sets 
Vote top 2 highest priorities - Easements/Streets 
Lots of user stories for easements 

Do a survey 123, remote voting? Will forward on the user stories/use case.  

![image](https://user-images.githubusercontent.com/21112975/74265903-f709b480-4cc8-11ea-8721-3c17da981c22.png)
 
### GIMGB: Geospatial Information Management Capability Road Map 2019-2022 
![image](https://user-images.githubusercontent.com/21112975/74265938-0557d080-4cc9-11ea-9a85-6bd749743990.png)

![image](https://user-images.githubusercontent.com/21112975/74265956-0d177500-4cc9-11ea-928c-fbee4a586859.png)

### DOING SWIMLANE 
ArcGIS Urban Tool - need to reload the data 
 
### Skype/Teams 
CTM has removed Skype from their computers and are only using Teams. We should migrate our users to Teams as the communication tool.  

### ESRI UC Attendance  
36 on the list 
Not everyone has registered 
30 registered 
to add extra credits? 
 
### Change Management Consulting 
Still ongoing 

### GIS Bloomfire 
New site

**Comment by dianamartin** [comment]
@jaime-mckeown I added my notes

**Comment by jaime-mckeown** [comment]
Thank you! @dianamartin
