### ISSUE TITLE
Create GIS Staffing Schedule

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-geospatial#593]

**Comment by johnclary** [comment]
@jaime-mckeown get schedule time slots from Ryan Mooney

**Comment by dianamartin** [comment]
File Path: G:\ATD\ATD_GIS\Office_of_Special_Events\SXSW\SXSW_2020\SXSW_2020_Command_Center

**Comment by jaime-mckeown** [comment]
@dianamartin Ryan sent me a link to the Command Center Schedule. Their shifts are 7am-4pm and 3pm-12am Fri 3/13 to Sat 3/21. The schedule that you made should work well with their overlap.

**Comment by jaime-mckeown** [comment]
After GIS Planning Meeting with GIS SPOCs, sent out link to Command Center Schedule so hopefully we can get some help staffing besides just ATD.
