### ISSUE TITLE
Export CSV from CIP feature class

### ISSUE THREAD

**Issue by amenity** [cityofaustin/atd-geospatial#615]
## GIS Service Request ##

**Requester:**
Amenity 

**Issue Description:**
A CSV export of the CIP feature class so that we can review the tabular data structure for[ Mobility Project Database research](https://github.com/cityofaustin/atd-mobility-project-database/issues/41). 

**Resolution / Service Provided:**

**Comment by amenity** [comment]
Spoke with @alan-deanda about this last Friday. Not hugely urgent. :)
Can be uploaded [here](https://drive.google.com/drive/folders/11PgHsCh-KgEnputC_O3512cYxNGKvQr-).

**Comment by alan-deanda** [comment]
@amenity I've uploaded the csv to our google drive.

**Comment by amenity** [comment]
Thanks, @alan-deanda 🙏
