### ISSUE TITLE
Review DRAFT Regulation Data

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-geospatial#67]
Kyle from AECOM sent over email about the draft regulations.

Downloaded here: 
`G:\ATD\ATD_GIS\Traffic_Engineering\AECOM_Staff_Augmentation\data_export`

**Comment by dianamartin** [comment]
I've downloaded file and added it to folder. Going to put into an .mxd to review.

**Comment by johnclary** [comment]
I believe all questions were answered. closing. CC @dianamartin
