### ISSUE TITLE
GeoEvent Jumpstart - Signals Request

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#68]
- Received an email from Marna that today was the last day to submit requests to add to the GeoEvent Jumstart. I asked Diana about it since I thought we were interested in using it for a possible project. She directed me to Joshil in the Signals group.
- Joshil shared with me that they are interested in using GeoEvent to create a reliable data stream for cell modems on Fire/EMS vehicles for an upcoming project. They want to use the data stream to migrate to pre-emption for the signals to detect emergency vehicles from the current system where the driver sends a signal to change the light.

**Comment by johnclary** [comment]
@jaime-mckeown i'd like to know more about the source data—what format is it in? does it come from an API? what protocol does that API use?

and the data destination—what format does the data need to be in? does the destination system have an API? what protocol does that API use? how frequently does the data need to be updated?

**Comment by jaime-mckeown** [comment]
@johnclary At this point I believe they only have sample data. Below is the email I received from Joshil regarding the data.

> Unfortunately have not been able to get any data from the modem as an example but there is a standard format. I believe Brian Craig (CCed) may have an example of the data he received but this is what I found online of what the data would look like:
> 
> $GPGGA,181908.00,3404.7041778,N,07044.3966270,
> W,4,13,1.00,495.144,M,29.200,M,0.10,0000*40
> The data is explained in this link (https://www.gpsworld.com/what-exactly-is-gps-nmea-data/).
> 
> Additionally, we would want 4 seconds latency for this data stream but no more than 6 seconds. This is to best simulate the field conditions. Let me know if you have further questions!
>

**Comment by jaime-mckeown** [comment]
@johnclary The conversation of data came up yesterday after I emailed Marna to let her know that Signals was interested in using GeoEvent. Yesterday was the cut-off for submitting use-cases to her for the Jumpstart that's coming up with Esri.

**Comment by jaime-mckeown** [comment]
Brian stopped by, said he would have data to use at the GeoEvent Jumpstart for testing.

**Comment by jaime-mckeown** [comment]
Attended the GeoEvent Subcommittee meeting yesterday. It was very short, Marna wanted any feedback for requested case studies, no one had any. She stated that the committee would not be meeting for a couple months since she now has to get the Jumpstart approved through the GIMOB. She's hoping the Jumpstart will take place at the end of July/beginning of August. She will find out the required data format from Esri. I emailed Joshil to keep him posted.

**Comment by jaime-mckeown** [comment]
Workshop is next week, will be meeting with Esri next Tuesday, Joshil will be attending.

**Comment by jaime-mckeown** [comment]
Workshop 11/5/19
- Joshil gave an introduction to the team about what they are trying to do with pre-emption for emergency vehicles and buses
- 6 second maximum for timing, would like it to be an low as possible
- Current cell modem on emergency vehicles is a closed system for dispatch
- 2nd cell modem will be open, ATD to use this modem for receiving AVL data
- 3rd cell modem is in the works for Fleet Services to maintain vehicle health for all city vehicles (Connected Vehicles Project)
- Fire Department has Fire Viewer Geocortex application for Fire Chief's, CTM wants to improve the lag
- Public Safety is currently working on a regional CAD for sharing data across counties (Travis and Williamson) is the biggest issue currently
- Joshil talked about grant funding being available, and that TriTech is willing to help build connection to connect to the AVL data
- Multiple groups want direct AVL feeds for different purposes
	- Fire
	- EMS
	- ATD
- Cell modem can be programmed to output to different types, it's just a setting. GeoEvent can handle multiple inputs as well.
- Hexagon is the CAD provider for San Jose, they have implemented pre-emption for emergency vehicles
- Signals has a $ 2-3 million for a grant to get this system up and going
- Esri IoT Solution - AGOL
	- New solution by Esri
- Andrew will talk to Marna and Sherri about the project going on with Williamson County with sharing data
- Will do a test with GeoEvent to see if it can read the data format and see the outputs from GeoEvent
- ATD getting grant money end of November 2019
	- Start looking for vendors next Spring
	- Hopefully start prototype next fall

**Comment by jaime-mckeown** [comment]
I spoke with Brian Craig about yesterday's meeting, he was curious what my take was after talking to Joshil about it.
- Both Joshil and I were under the impression that it was supposed to be a workshop where they would be using the data stream and demonstrating the software... 
- It felt more like a pre-workshop to the workshop. It was mostly discussion about what ATD is wanting to use GeoEvent for with CTM. Esri reps were not really involved in the conversation, which I thought was strange since we waited months to have this meeting with them.
- Brian informed me that 6 second timing interval is inaccurate, they are looking for more like 2 seconds. I told him that CTM seemed overwhelmed by 6 seconds, so 2 seconds may be pretty challenging for them.
- He mentioned that this solution would be the most inexpensive for ATD as they would only need to maintain the server. Brian is curious if ATD could pay to maintain their own GeoEvent Server to ensure this could move forward.
- Joshil and Brian plan to prepare a document outlining exactly what they need from CTM to keep this project moving forward using GeoEvent.
- It was a starting point, got Joshil into conversations with CTM to help them decide on the best direction they want to go with the preemption project.
- It also helped me to get a basic understanding of what Arterial Management is doing with this project so I can provide better GIS assistance to their group moving forward.

**Comment by johnclary** [comment]
@jaime-mckeown @amenity i would be interested in sitting down with Joshil and Brian to understand the specific ETL process they need to run. we have in-house IT that could do this better than geoevent, depending on some technical specifics.
