### ISSUE TITLE
ROW_Inspector_Zones published to AGOL

### ISSUE THREAD

**Issue by jaime-mckeown** [cityofaustin/atd-geospatial#97]
- John has requested that the row_inspector_zones layer be published to AGOL. I will publish it via ATD_Publisher to get it in AGOL ASAP. I will also submit a CTM help desk ticket to get it published as an authoritative data source. Once that is done, I will notify John so he can make the switch and the ATD_Publisher version can be deleted.

**Comment by johnclary** [comment]
Service is here:
https://austin.maps.arcgis.com/home/item.html?id=6f8494ac82154c11a09054eb6345d812

Layer def:
https://services.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/row_inspector_zones/FeatureServer/0?token=huw1l196vlb4tYczgBYimygYTaYyNNRcm4xV3ZdOnLDwP_AuKz5nri7aG-fAnIp8hK1W1oTGZFpcbTpuwC6Kpsxosh-cB6oPySROSJtvOdNU6Gm9PynbCHMi6FOW3wi0WhDNoNlDyGN1LulbMLh8CSAQncQGcwHka16Mz10O1GWUNQMr_7L5AVZZPXbSaG5299JdrNWAuS4Mk1khNYSVEQtTipuEej00Qiz-fTzoCz5CnyIX8wbLkByrJngewOH9

**Comment by jaime-mckeown** [comment]
@johnclary - TRANSPORTATION_row_inspector_zones has been published by CTM on AGOL. Please let me know when you've changed over so I can delete the version I published.
http://austin.maps.arcgis.com/home/item.html?id=9faba45a08524a458dd346c49361180f

**Comment by johnclary** [comment]
@jaime-mckeown done! I went ahead and deleted the layer you published. thanks for knocking this out.
